application: gyroplaneio
version: 2
runtime: python27
api_version: 1
threadsafe: no

libraries:                                                                      
- name: markupsafe                                                              
  version: latest 

handlers:
- url: /echoecho/.*
  secure: optional
  script: app.echo

- url: .*
  script: app.app
